### ISSUE TITLE
Error in Leave Deduct [Holidays inside leaves]

### ISSUE THREAD

**Issue by msf458** [saifuldipak/attendance#10]
When Apply for  Leave Application with Holiday in between, App Deducting Leave and also deducting leave as "Holidays inside leaves". 

E.g User apply for Casual Leave from 9/03/2023 to 12/03/2023. App Deduct 4 leaves as application and also 2 leaves as Holiday inside Leaves. Total of 6 leaves.

**Comment by saifuldipak** [comment]
Bug fixed
