### ISSUE TITLE
Exception Error Handling Message

### ISSUE THREAD

**Issue by msf458** [saifuldipak/attendance#11]
When there is Blank Cell or Row in Attendance Data File, During upload app gives Exception Error. 

`ValueError: cannot convert float NaN to integer`

It will be helpful if it provide more meaningful Message. 
e.g

`Rows or Cells cannot be Empty. Check your File`

**Comment by saifuldipak** [comment]
Condition added to check any blank cell in employee id column(first column) in the excell sheet and give error message to the user. This will avoid the program to raise a ValueError exception in case of blank cell.
