### ISSUE TITLE
Duty Schedule Table Issue

### ISSUE THREAD

**Issue by msf458** [saifuldipak/attendance#13]
Duty Schedule Table showing column beyond the month end date. Also Duty Schedules are auto created for upcoming months. 

 [https://www.dropbox.com/scl/fi/ry41uyaqy03wu73lq8sn5/Screenshot-from-2023-08-01-09-30-40.png?rlkey=q11b2x7kzfdkonvneom19xbzw&dl=0](url)

**Comment by saifuldipak** [comment]
Issue fixed with this commit (5781b)
